learn-rails/config/routes.rb
Rails.application.routes.draw do

  
  LearnRails::Application.routes.draw do
    resources :contacts, only: [:new, :create]  
    root to: 'visitors#new'    
  end
  
  
end

learn-rails/app/models/contact.rb
class Contact < ActiveRecord::Base
has_no_table

column :name, :string
column :email, :string
column :content, :string

validates_presence_of :name 
validates_presence_of :email
validates_presence_of :content
validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
validates_length_of :content, :maximum => 500
end

learn-rails/app/models/owner.rb
class Owner
  
  def name
    name = 'Jos Kelleners'
  end
  def birthdate
    birthdate = Date.new(1990,12,22)
  end
  
  def countdown
    today =  Date.today
    birthday = Date.new(today.year, birthdate.month, birthdate.day)
    if birthday > today
      countdown = (birthday - today).to_i
    else
      countdown =  (birthday.next_year -today).to_i
    end 
  end
end
  
  
  
  

learn-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

learn-rails/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new 
    @contact = Contact.new
  end
  
  def create 
    @contact=Contact.new(secure_params)
    if @contact.valid?
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end
    
    private
    
    def secure_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

learn-rails/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  
  def new
    Rails.logger.debug 'DEBUG : entering new method'
    @owner = Owner.new
  end
end

learn-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

learn-rails/app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3> 
<div class="form">
  <%= simple_form_for @contact do |form| %>
  <%= form.error_notification %>
  <%= form.input :name, autofocus: true %>
  <%= form.input :email %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div> 
  

learn-rails/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

learn-rails/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

learn-rails/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %> </li>
<li><%= link_to 'Contact', new_contact_path %> </li>

learn-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

learn-rails/app/views/pages/about.html.erb
<% content_for :title do %>About<% end  %> 
<p>2014 loopt ten einde. Tijd om de balans op te maken en kort terug te blikken wat het afgelopen jaar ons heeft gebracht. Uiteraard wordt de beleving van dit sportjaar gekleurd door een ieders  eigen ervaring.  Bij de een ging het wat minder als gevolg van een ziekte of slepende blessure. De ander werd juist extra gemotiveerd omdat hij of zij werd geselecteerd voor de talentontwikkeling of nationaal team of een medaille behaalde bij een van de wedstrijden. Iedereen heeft zijn eigen rol en verwachtingen binnen onze vereniging, maar samen zijn wij de Reddingsbrigade Echt. Een hechte club van enthousiaste sporters, trainers, instructeurs, ouders  en vrijwilligers.  Als bestuur kijken wij tevreden en trots terug op een sportief succesvol verlopen 2014.

Vrijdag 2 januari nieuwjaarsborrel, na de training om 22.15 uur, we proosten dan alvast op een voorspoedig en succesvol 2015!!
Zaterdag 3 januari beginnen ook weer de trainingen voor de wedstrijdleden.  </p>

learn-rails/app/views/visitors/new.html.erb
<h2>Home</h3>
<p> Welcome to the home of <%=@owner.name %>.</p>
<p> I was born on <%= @owner.birthdate %>. </p>
<p> Only <%=@owner.countdown %> days until my birthday! </p> 